### ISSUE TITLE
FileExistsError, first time assembly testing was ok but not on 2nd time onward

### ISSUE THREAD

**Issue by xiaolaba** [kcelebi/riscv-assembler#17] opened 2023-02-12 06:38 UTC
hi, this is log,

```
C:\Users\user0\riscv-assembler\tests\assembly>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from riscv_assembler.convert import AssemblyConverter
>>> cnv = AssemblyConverter()
>>> cnv.convert("test0.s")
-----Writing to binary file-----
Output file: test0.bin
Number of instructions: 1
>>> #outputs to binary file simple.bin
...
>>> from riscv_assembler.convert import AssemblyConverter
>>> cnv = AssemblyConverter()
>>> cnv.convert("test0.s")
-----Writing to binary file-----
Output file: test0.bin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user0\AppData\Local\Programs\Python\Python37-32\lib\site-packages\riscv_assembler\convert.py", line 589, in convert
    return self.__post()
  File "C:\Users\user0\AppData\Local\Programs\Python\Python37-32\lib\site-packages\riscv_assembler\convert.py", line 533, in __post
    os.mkdir(f"{fname[:-2]}/bin")
FileExistsError: [WinError 183] File/Folder existed, could not create the file or folder: 'test0/bin'
>>> #outputs to binary file simple.bin

```

**Comment by kcelebi** [comment] 2023-04-11 21:33
Given that this versioning is deprecated and the issue is solved in the new version, I will close this comment.

Note: I won't be updating this repository anymore as it has been moved to [celebi-pkg/riscv-assembler](https://www.github.com/celebi-pkg/riscv-assembler). The Python deployments and latest code are being updated there.

**Closed by kcelebi** 2023-04-11 21:33 UTC
